SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_TITLE = "ComuniCook"
RADIUS = 20
MOVEMENT_SPEED = 5

IDLE_TEXTURE_INDEX = 1
MOVE_UP_TEXTURE_INDEX = 9
MOVE_DOWN_TEXTURE_INDEX = 0
MOVE_LEFT_TEXTURE_INDEX = 3
MOVE_RIGHT_TEXTURE_INDEX = 6

INITIAL_COMUNITY_SIZE = (3, 5)
